name: Build and push Docker image

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    # Times are UTC so this *should* run at midnight Eastern... :^)
    - cron: "0 4 * * 1"

# Wish I could do this with a matrix but it doesn't play nice with
# package publishing
env:
  CONTAINER_REGISTRY: "ghcr.io"
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_PLATFORMS: "linux/amd64,linux/arm64"
  # https://github.com/orgs/community/discussions/45969#discussioncomment-5334871
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    steps:
    - uses: actions/checkout@v4

    - id: vars
      run: |
        echo "should_push=${{ github.event_name != 'pull_request' && github.ref_name == github.event.repository.default_branch }}" >> "$GITHUB_OUTPUT"

    - name: Log in to GitHub Container Registry
      if: ${{ steps.vars.outputs.should_push == 'true' }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate Docker metadata
      uses: docker/metadata-action@v5
      id: meta
      with:
        images: ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}
        labels: |
          description=Create a SOCKS5 server using a WireGuard config
          org.opencontainers.image.title=socks5-wireguard
          org.opencontainers.image.description=Create a SOCKS5 server using a WireGuard config
          org.opencontainers.image.vendor=${{ github.repository_owner }}
          org.opencontainers.image.licenses=AGPL-3.0-or-later
        tags: |
          type=raw,value=latest,enable={{is_default_branch}},priority=2000
          type=schedule

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: ${{ env.DOCKER_PLATFORMS }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      id: build_push
      uses: docker/build-push-action@v6
      with:
        context: .
        # Only push if we've pushed code to the default (main) branch
        push: ${{ steps.vars.outputs.should_push == 'true' }}
        platforms: ${{ env.DOCKER_PLATFORMS }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        annotations: ${{ steps.meta.outputs.annotations }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Publish Docker image attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}
        subject-digest: ${{ steps.build_push.outputs.digest }}
        push-to-registry: true
        show-summary: true
